boca_plantel = {
    "Sergio Romero": {"Edad": 35, "Posición": "Portero", "Valor de Mercado": 15000000, "Valoración": 8},
    "Leandro Brey": {"Edad": 20, "Posición": "Portero", "Valor de Mercado": 6000000, "Valoración": 7},
    "Marcelo Weigandt": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 7000000, "Valoración": 9},
    "Facundo Roncaglia": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 9},
    "Nicolás Figal": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 9000000, "Valoración": 7},
    "Frank Fabra": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 7000000, "Valoración": 9},
    "Luis Advíncula": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 12000000, "Valoración": 9},
    "Pol Fernández": {"Edad": 31, "Posición": "Volante", "Valor de Mercado": 9000000, "Valoración": 8},
    "Martín Payero": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 7000000, "Valoración": 7},
    "Juan Ramírez": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 5000000, "Valoración": 8},
    "Cristian Medina": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 9000000, "Valoración": 9},
    "Miguel Merentiel": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 7000000, "Valoración": 8},
    "Darío Benedetto": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 12000000, "Valoración": 8},
    "Sebastián Villa": {"Edad": 29, "Posición": "Delantero", "Valor de Mercado": 14000000, "Valoración": 9},
    "Ezequiel Zeballos": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 7000000, "Valoración": 8}
}
river_plantel = {
    "Franco Armani": {"Edad": 34, "Posición": "Portero", "Valor de Mercado": 10000000, "Valoración": 9},
    "Germán Lux": {"Edad": 39, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 6},
    "Gonzalo Montiel": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 20000000, "Valoración": 8},
    "Héctor Martínez": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 7000000, "Valoración": 7},
    "David Martínez": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 8000000, "Valoración": 7},
    "Jonatan Maidana": {"Edad": 36, "Posición": "Defensor", "Valor de Mercado": 5000000, "Valoración": 8},
    "Milton Casco": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 9000000, "Valoración": 8},
    "Enzo Pérez": {"Edad": 35, "Posición": "Volante", "Valor de Mercado": 12000000, "Valoración": 9},
    "Nicolás De La Cruz": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 15000000, "Valoración": 8},
    "Enzo Fernández": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 10000000, "Valoración": 7},
    "Bruno Zuculini": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 7000000, "Valoración": 7},
    "Julián Álvarez": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 20000000, "Valoración": 9},
    "Matías Suárez": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 12000000, "Valoración": 8},
    "Rafael Borré": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 18000000, "Valoración": 9},
    "Jorge Carrascal": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 10000000, "Valoración": 7}
}
racing_club_plantel = {
    "Gabriel Arias": {"Edad": 34, "Posición": "Portero", "Valor de Mercado": 8000000, "Valoración": 8},
    "Juan José Cáceres": {"Edad": 22, "Posición": "Portero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Leonardo Sigali": {"Edad": 34, "Posición": "Defensor", "Valor de Mercado": 5000000, "Valoración": 8},
    "Nery Domínguez": {"Edad": 31, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 7},
    "Eugenio Mena": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 6000000, "Valoración": 8},
    "Joquín Novillo": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 7},
    "Juan José Cáceres": {"Edad": 21, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7},
    "Leonel Miranda": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 6000000, "Valoración": 7},
    "Matías Rojas": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 9000000, "Valoración": 8},
    "Ignacio Piatti": {"Edad": 36, "Posición": "Volante", "Valor de Mercado": 7000000, "Valoración": 8},
    "Carlos Alcaraz": {"Edad": 18, "Posición": "Volante", "Valor de Mercado": 5000000, "Valoración": 7},
    "Anibal Moreno": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Tomás Chancalay": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 8000000, "Valoración": 7},
    "Darío Cvitanich": {"Edad": 37, "Posición": "Delantero", "Valor de Mercado": 4000000, "Valoración": 7},
    "Nicolás Reniero": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 6000000, "Valoración": 8}
}
independiente_plantel = {
    "Sebastián Sosa": {"Edad": 35, "Posición": "Portero", "Valor de Mercado": 5000000, "Valoración": 8},
    "Milton Álvarez": {"Edad": 33, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Alan Franco": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 10000000, "Valoración": 8},
    "Juan Manuel Insaurralde": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 7},
    "Sergio Barreto": {"Edad": 21, "Posición": "Defensor", "Valor de Mercado": 6000000, "Valoración": 7},
    "Fabricio Bustos": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 8000000, "Valoración": 8},
    "Lucas Rodríguez": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 7000000, "Valoración": 8},
    "Ayrton Costa": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7},
    "Alan Velasco": {"Edad": 19, "Posición": "Volante", "Valor de Mercado": 12000000, "Valoración": 9},
    "Lucas Romero": {"Edad": 27, "Posición": "Volante", "Valor de Mercado": 9000000, "Valoración": 8},
    "Domingo Blanco": {"Edad": 27, "Posición": "Volante", "Valor de Mercado": 6000000, "Valoración": 7},
    "Andrés Roa": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 7000000, "Valoración": 7},
    "Silvio Romero": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 8000000, "Valoración": 9},
    "Jonathan Menéndez": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 5000000, "Valoración": 7},
    "Braian Martínez": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 6000000, "Valoración": 8},
    "Juan Manuel Insaurralde": {"Edad": 36, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7}
}
velez_plantel = {
    "Lucas Hoyos": {"Edad": 31, "Posición": "Portero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Matías Borgogno": {"Edad": 20, "Posición": "Portero", "Valor de Mercado": 500000, "Valoración": 6},
     "Luis Abram": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 8000000, "Valoración": 8},
    "Miguel Brizuela": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 7},
    "Tomás Guidara": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7},
    "Francisco Ortega": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 5000000, "Valoración": 7},
    "Ricardo Álvarez": {"Edad": 32, "Posición": "Volante", "Valor de Mercado": 4000000, "Valoración": 7},
    "Pablo Galdames": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 7000000, "Valoración": 8},
    "Lucas Janson": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 6000000, "Valoración": 7},
    "Agustín Bouzat": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 5000000, "Valoración": 7},
    "Juan Martín Lucero": {"Edad": 27, "Posición": "Delantero", "Valor de Mercado": 5000000, "Valoración": 7},
    "Thiago Almada": {"Edad": 20, "Posición": "Delantero", "Valor de Mercado": 10000000, "Valoración": 9},
    "Maximiliano Romero": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 9000000, "Valoración": 8},
    "Juan Martín Lucero": {"Edad": 27, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7}
}
san_lorenzo_plantel = {
    "Sebastián Torrico": {"Edad": 42, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 7},
    "José Devecchi": {"Edad": 25, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Gonzalo Rodríguez": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 8},
    "Fabián Licha": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 6},
    "Gino Peruzzi": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 7},
    "Diego Braghieri": {"Edad": 35, "Posición": "Defensor", "Valor de Mercado": 2500000, "Valoración": 7},
    "Bruno Pittón": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 3500000, "Valoración": 7},
    "Juan Ramírez": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 5000000, "Valoración": 8},
    "Óscar Romero": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 8000000, "Valoración": 9},
    "Ángel Romero": {"Edad": 30, "Posición": "Volante", "Valor de Mercado": 8000000, "Valoración": 8},
    "Nahuel (EL PERRITO) BARRIOS": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 3000000, "Valoración": 7},
    "Álex Díaz": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 4000000, "Valoración": 7},
    "Fernando Monetti": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Adolfo Gaich": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 6000000, "Valoración": 8},
    "Franco Di Santo": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 3500000, "Valoración": 7}
}
huracan_plantel = {
    "Anthony Silva": {"Edad": 38, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Marcos Díaz": {"Edad": 35, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Rafael Ferrario": {"Edad": 20, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Adrián Arregui": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 2500000, "Valoración": 7},
    "Saúl Salcedo": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7},
    "Lucas Merolla": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 6},
    "Ezequiel Bonifacio": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 2500000, "Valoración": 7},
    "Franco Cristaldo": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 6},
    "Alexis Gómez": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 3000000, "Valoración": 7},
    "Mauro Bogado": {"Edad": 35, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 7},
    "Norberto Briasco": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 4000000, "Valoración": 8},
    "Andrés Chávez": {"Edad": 31, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Lucas Barrios": {"Edad": 37, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Juan Garro": {"Edad": 30, "Posición": "Delantero", "Valor de Mercado": 1800000, "Valoración": 6},
    "Fernando Coniglio": {"Edad": 31, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7}
}
argentinos_juniors_plantel = {
    "Lucas Chaves": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Federico Lanzillotta": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Carlos Quintana": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7},
    "Miguel Torrén": {"Edad": 34, "Posición": "Defensor", "Valor de Mercado": 2500000, "Valoración": 7},
    "Jonathan Sandoval": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 6},
    "Elías Gómez": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 8},
    "Gabriel Florentín": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 2500000, "Valoración": 7},
    "Franco Moyano": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 1800000, "Valoración": 6},
    "Gabriel Carabajal": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 3500000, "Valoración": 7},
    "Matías Romero": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 3000000, "Valoración": 7},
    "Gabriel Ávalos": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 4000000, "Valoración": 7},
    "Lucas Ambrogio": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 6},
    "Gabriel Hauche": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 1800000, "Valoración": 7},
    "Mateo Coronel": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 6},
    "Nicolás Silva": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 7}
}
central_cordoba_plantel = {
    "Diego Rodríguez": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 7},
    "César Rigamonti": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Ismael Quilez": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 6},
    "Jonathan Bay": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Gonzalo Bettini": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Nicolás Correa": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Facundo Melivillo": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 6},
    "Leonel Ferroni": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Federico Andueza": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Leandro Vella": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Lucas Brochero": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Cristian Vega": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 900000, "Valoración": 7},
    "Gervasio Núñez": {"Edad": 33, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Juan Galeano": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Facundo Silva": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Santiago Rosales": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 900000, "Valoración": 7},
    "Pablo Argañaraz": {"Edad": 27, "Posición": "Delantero", "Valor de Mercado": 700000, "Valoración": 6}
}

belgrano_plantel = {
    "César Rigamonti": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Nahuel Losada": {"Edad": 23, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Juan Barinaga": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Ignacio Vázquez": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Gabriel Gómez": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7},
    "Joel Sacks": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Tobías Ostchega": {"Edad": 20, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 6},
    "Hernán Bernardello": {"Edad": 34, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Martín Rivero": {"Edad": 35, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Tomás Attis": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Ulises Sánchez": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Gastón González": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Marcos Rivadero": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 700000, "Valoración": 6},
    "Gonzalo Lencina": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Bruno Amione": {"Edad": 20, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Marcelo Estigarribia": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 900000, "Valoración": 7}
}
talleres_plantel = {
    "Guido Herrera": {"Edad": 30, "Posición": "Portero", "Valor de Mercado": 3000000, "Valoración": 8},
    "Marcos Díaz": {"Edad": 35, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Nahuel Tenaglia": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 6000000, "Valoración": 8},
    "Rafael Pérez": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 7},
    "Piero Hincapié": {"Edad": 19, "Posición": "Defensor", "Valor de Mercado": 8000000, "Valoración": 8},
    "Augusto Schott": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 6},
    "Federico Navarro": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 6000000, "Valoración": 8},
    "Francisco Apaolaza": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 4000000, "Valoración": 7},
    "Diego Valoyes": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 5000000, "Valoración": 7},
    "Nahuel Bustos": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 7000000, "Valoración": 8},
    "Carlos Auzqui": {"Edad": 30, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Mateo Retegui": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 4000000, "Valoración": 7},
    "Michael Santos": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 5000000, "Valoración": 8},
    "Ignacio Irigo": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 3500000, "Valoración": 7},
    "Leandro Visani": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7}
}

instituto_plantel = {
    "Jorge Carranza": {"Edad": 36, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Milton Álvarez": {"Edad": 28, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Facundo Agüero": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Franco Flores": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Emiliano Endrizzi": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Lucas Landa": {"Edad": 21, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 6},
    "Ezequiel Bonacorso": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Ignacio Antonio": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Matías Antonio": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Mateo Bajamich": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 7},
    "Rodrigo Garro": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Malcom Braida": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 7},
    "Martín Pino": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 700000, "Valoración": 6},
    "Agustin Passadore": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Tisano": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 7}
}
rosario_central_plantel = {
    "Jeremías Ledesma": {"Edad": 28, "Posición": "Portero", "Valor de Mercado": 2500000, "Valoración": 7},
    "Mauricio Caranta": {"Edad": 42, "Posición": "Portero", "Valor de Mercado": 500000, "Valoración": 6},
    "Damián Martínez": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 5000000, "Valoración": 8},
    "Jonathan Bottinelli": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 7},
    "Nahuel Molina": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 6000000, "Valoración": 8},
    "Joel López Pissano": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 6},
    "Emmanuel Ojeda": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 3500000, "Valoración": 7},
    "Diego Zabala": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 3000000, "Valoración": 6},
    "Fabián Rinaudo": {"Edad": 34, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 7},
    "Luciano Ferreyra": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 6},
    "Marco Ruben": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 5000000, "Valoración": 8},
    "Lucas Gamba": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 4000000, "Valoración": 7},
    "Joao Rodríguez": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Luciano Cingolani": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 6},
    "Alejo Véliz": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 2500000, "Valoración": 7},
    "Mateo Bounanotte": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7}
}

newells_plantel = {
    "Alan Aguerre": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 3000000, "Valoración": 7},
    "Ramiro Macagno": {"Edad": 27, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Manuel Capasso": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 2500000, "Valoración": 7},
    "Cristian Lema": {"Edad": 31, "Posición": "Defensor", "Valor de Mercado": 4000000, "Valoración": 8},
    "Yonathan Cabral": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 7},
    "Facundo Nadalín": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 6},
    "Braian Rivero": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 3500000, "Valoración": 7},
    "Julián Fernández": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 4000000, "Valoración": 7},
    "Mauro Formica": {"Edad": 33, "Posición": "Volante", "Valor de Mercado": 3000000, "Valoración": 7},
    "Enzo Cabrera": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 6},
    "Maximiliano Rodríguez": {"Edad": 40, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Ignacio Scocco": {"Edad": 36, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Franco Negri": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 6},
    "Jonás Acevedo": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Lionel Andres Mezi": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 2500000, "Valoración": 7},
    "Sergio Ramas": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 7}
}
godoy_cruz_plantel = {
    "Juan Espínola": {"Edad": 31, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 7},
    "Juan Cruz Bolado": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 500000, "Valoración": 6},
    "Mauro Dos Santos": {"Edad": 34, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 7},
    "Néstor Breitenbruch": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Leonel González": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 6},
    "Renzo Tesuri": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Federico Vismara": {"Edad": 36, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Agustín Manzur": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Martín Ojeda": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Brian Alferez": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Tomás Badaloni": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Ezequiel Bullaude": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 6},
    "Matías Ramírez": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 900000, "Valoración": 6},
    "Gabriel Ávalos": {"Edad": 31, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 7},
    "Neymor": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Virgil Van Dique": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 7}
}

platense_plantel = {
    "Jorge De Olivera": {"Edad": 38, "Posición": "Portero", "Valor de Mercado": 500000, "Valoración": 6},
    "Andrés Desábato": {"Edad": 44, "Posición": "Portero", "Valor de Mercado": 200000, "Valoración": 6},
    "Nicolás Zalazar": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Lucas Acevedo": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Hernán Lamberti": {"Edad": 36, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Augusto Schott": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 6},
    "Lautaro Guzmán": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 7},
    "Roberto Bochi": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 400000, "Valoración": 6},
    "Agustín Palavecino": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Alejandro Lugones": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 300000, "Valoración": 6},
    "Facundo Curuchet": {"Edad": 29, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 7},
    "Daniel Vega": {"Edad": 39, "Posición": "Delantero", "Valor de Mercado": 400000, "Valoración": 6},
    "Agustín Palavecino": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Tobías Reinhart": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 500000, "Valoración": 6},
    "Luis Alberto Suarinaga": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 400000, "Valoración": 7},
    "Thiago Silvador": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 7}
}

barracas_central_plantel = {
    "Ezequiel Cacace": {"Edad": 28, "Posición": "Portero", "Valor de Mercado": 400000, "Valoración": 6},
    "Elías Gómez": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 200000, "Valoración": 6},
    "Facundo Oreja": {"Edad": 36, "Posición": "Defensor", "Valor de Mercado": 500000, "Valoración": 7},
    "Gonzalo Paz": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 400000, "Valoración": 6},
    "Enzo Ortíz": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Federico Mazur": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Carlos Arce": {"Edad": 32, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Lucas Colitto": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 400000, "Valoración": 6},
    "Cristian Carrizo": {"Edad": 35, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Leandro Puig": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 300000, "Valoración": 6},
    "Jonathan Herrera": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 700000, "Valoración": 7},
    "Gonzalo Rodríguez": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 500000, "Valoración": 6},
    "Facundo Castro": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Maximiliano Salas": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 700000, "Valoración": 6},
    "Marco Reutilizable": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 300000, "Valoración": 7},
    "Carloz Derechoz": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 400000, "Valoración": 7}
}
huracan_plantel = {
    "Anthony Silva": {"Edad": 38, "Posición": "Portero", "Valor de Mercado": 600000, "Valoración": 7},
    "Facundo Cambeses": {"Edad": 24, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 8},
    "Saúl Salcedo": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 7},
    "Raúl Lozano": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Cristian Núñez": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "César Ibáñez": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7},
    "Adrián Calello": {"Edad": 33, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 8},
    "Esteban Rolón": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 8},
    "Agustín Curruhinca": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Franco Cristaldo": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Andrés Chávez": {"Edad": 30, "Posición": "Delantero", "Valor de Mercado": 1800000, "Valoración": 8},
    "Norberto Briasco": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Agustín Curruhinca": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1600000, "Valoración": 8},
    "Franco Niell": {"Edad": 38, "Posición": "Delantero", "Valor de Mercado": 500000, "Valoración": 6},
    "Cristiano Rodando": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 7},
    "Eder Limitao": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7}
}

banfield_plantel = {
    "Facundo Altamirano": {"Edad": 31, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 7},
    "Mauricio Arboleda": {"Edad": 25, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Alexis Maldonado": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 3000000, "Valoración": 8},
    "Renato Civelli": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Lucas Abecasis": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Claudio Bravo": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Martín Payero": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 8},
    "Jesús Dátolo": {"Edad": 37, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 7},
    "Luciano Gómez": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Martín Lucero": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 6},
    "Juan Cruz Fontana": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Agustín Urzi": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 2500000, "Valoración": 8},
    "Luciano Pons": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Mauricio Cuero": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Luis Alberto Nachisol": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Patricio Olmedo": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7}
}

arsenal_plantel = {
    "Nicolás Navarro": {"Edad": 36, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Maximiliano Gagliardo": {"Edad": 33, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Gastón Suso": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Franco Sbuttoni": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Jonathan Bottinelli": {"Edad": 36, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Emiliano Papa": {"Edad": 37, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Leonel Picco": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Fernando Torrent": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Nicolás Castro": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Julián Navas": {"Edad": 27, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Jhonatan Candia": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Lucas Albertengo": {"Edad": 29, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Alan Ruiz": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Juan Kaprof": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 900000, "Valoración": 6},
    "Lautaro Nachi": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 7},
    "Claudio Valeriano Mommen": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 7}
}

estudiantes_plantel = {
    "Mariano Andújar": {"Edad": 37, "Posición": "Portero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Emiliano González": {"Edad": 23, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Fabián Noguera": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 7},
    "Nazareno Colombo": {"Edad": 21, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Agustín Rogel": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Facundo Mura": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Juan Sánchez Miño": {"Edad": 32, "Posición": "Volante", "Valor de Mercado": 1800000, "Valoración": 8},
    "Nicolás Pasquini": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 7},
    "Iván Gómez": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Julián Marchioni": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Federico González": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Rodrigo Bogado": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Martín Cauteruccio": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Juan Apaolaza": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 7},
    "Juan Noelia": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 7},
    "Danielito Carrera": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7}
}
gimnasia_plantel = {
    "Jorge Broun": {"Edad": 35, "Posición": "Portero", "Valor de Mercado": 1200000, "Valoración": 8},
    "Nelson Insfrán": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 7},
    "Maximiliano Coronel": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 7},
    "Germán Guiffrey": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Matías Melluso": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Lucas Licht": {"Edad": 39, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Harrinson Mancilla": {"Edad": 25, "Posición": "Volante", "Valor de Mercado": 1800000, "Valoración": 8},
    "Matías Miranda": {"Edad": 21, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Hernán Tifner": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Johann Carbonero": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 7},
    "Sebastián Cocimano": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Horacio Tijanovich": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Ezequiel Bonifacio": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Lucas Barrios": {"Edad": 37, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Micael Belen Macias": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 7},
    "Lorenao Machias": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7}
}

atletico_tucuman_plantel = {
    "Cristian Lucchetti": {"Edad": 43, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 8},
    "Alejandro Sánchez": {"Edad": 32, "Posición": "Portero", "Valor de Mercado": 600000, "Valoración": 6},
    "Mauro Osores": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Yonathan Cabral": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Agustín Lagos": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Federico Bravo": {"Edad": 27, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Guillermo Acosta": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Lucas Melano": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 900000, "Valoración": 6},
    "Cristian Erbes": {"Edad": 32, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Ramiro Carrera": {"Edad": 27, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Leonardo Heredia": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Augusto Lotti": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Juan Cruz Kaprof": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Paulista": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Carleto Viviano": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}
sarmiento_plantel = {
    "Manuel Vicentini": {"Edad": 34, "Posición": "Portero", "Valor de Mercado": 1200000, "Valoración": 8},
    "Facundo Daffonchio": {"Edad": 27, "Posición": "Portero", "Valor de Mercado": 600000, "Valoración": 6},
    "Martín García": {"Edad": 31, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Lautaro Geminiani": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7},
    "Nahuel Estevez": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Federico Mancinelli": {"Edad": 35, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Fabián Vargas": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Gabriel Graciani": {"Edad": 29, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Fernando Núñez": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Claudio Pombo": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Jonás Acevedo": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Benjamín Borasi": {"Edad": 23, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Joaquín Vivani": {"Edad": 20, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Maximiliano Fornari": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Gaston Leones": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Micaela Envolas": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}

tigre_plantel = {
    "Gonzalo Marinelli": {"Edad": 30, "Posición": "Portero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Marco Wolff": {"Edad": 27, "Posición": "Portero", "Valor de Mercado": 500000, "Valoración": 6},
    "Sebastián Prieto": {"Edad": 29, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7},
    "Ezequiel Rodríguez": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Facundo Monteseirín": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Diego Morales": {"Edad": 32, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Lucas Menossi": {"Edad": 28, "Posición": "Volante", "Valor de Mercado": 1100000, "Valoración": 7},
    "Tomás Fernández": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 900000, "Valoración": 7},
    "Nicolás Colazo": {"Edad": 31, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Diego Becker": {"Edad": 24, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Javier Toledo": {"Edad": 34, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Pablo Magnin": {"Edad": 32, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 7},
    "Carlos Luna": {"Edad": 39, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Enzo Díaz": {"Edad": 24, "Posición": "Delantero", "Valor de Mercado": 600000, "Valoración": 6},
    "Mateo Pusisneri": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Rolon Esteban": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}

colon_plantel = {
    "Leonardo Burián": {"Edad": 36, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 8},
    "Ignacio Chicco": {"Edad": 23, "Posición": "Portero", "Valor de Mercado": 600000, "Valoración": 6},
    "Facundo Garcés": {"Edad": 22, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 8},
    "Rafael Delgado": {"Edad": 31, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 7},
    "Paolo Goltz": {"Edad": 36, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Gonzalo Piovi": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Yeiler Góez": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 1800000, "Valoración": 8},
    "Christian Bernardi": {"Edad": 30, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 7},
    "Alex Vigo": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Federico Lértora": {"Edad": 32, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 6},
    "Wilson Morelo": {"Edad": 33, "Posición": "Delantero", "Valor de Mercado": 1800000, "Valoración": 8},
    "Tomás Chancalay": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Facundo Farías": {"Edad": 20, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Brian Fernández": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Facundo Loredo": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Cata Diaz": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}

union_plantel = {
    "Sebastián Moyano": {"Edad": 33, "Posición": "Portero", "Valor de Mercado": 1200000, "Valoración": 8},
    "Mauricio Castro": {"Edad": 25, "Posición": "Portero", "Valor de Mercado": 600000, "Valoración": 6},
    "Jonathan Galván": {"Edad": 30, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 7},
    "Juan Carlos Portillo": {"Edad": 32, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 7},
    "Matías Nani": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 700000, "Valoración": 6},
    "Claudio Corvalán": {"Edad": 33, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6},
    "Gabriel Carabajal": {"Edad": 27, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Ezequiel Cañete": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 900000, "Valoración": 7},
    "Kevin Zenón": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Mauro Pittón": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 700000, "Valoración": 6},
    "Federico Andrada": {"Edad": 28, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Juan Manuel García": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Gastón González": {"Edad": 25, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Matías Gallegos": {"Edad": 22, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 6},
    "Jorge Carrasco": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Matias Carreras": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}

defensa_y_justicia_plantel = {
    "Ezequiel Unsain": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 8},
    "Marcos Ledesma": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 7},
    "Adonis Frías": {"Edad": 21, "Posición": "Defensor", "Valor de Mercado": 2000000, "Valoración": 8},
    "Nicolás Tripichio": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 1500000, "Valoración": 7},
    "Héctor Martínez": {"Edad": 26, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Franco Paredes": {"Edad": 25, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Francisco Cerro": {"Edad": 34, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Eugenio Isnaldo": {"Edad": 30, "Posición": "Volante", "Valor de Mercado": 1000000, "Valoración": 7},
    "Washington Camacho": {"Edad": 30, "Posición": "Volante", "Valor de Mercado": 900000, "Valoración": 6},
    "Rafael Delgado": {"Edad": 33, "Posición": "Volante", "Valor de Mercado": 800000, "Valoración": 6},
    "Julián Álvarez": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 2000000, "Valoración": 8},
    "Francisco Pizzini": {"Edad": 27, "Posición": "Delantero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Braian Romero": {"Edad": 30, "Posición": "Delantero", "Valor de Mercado": 1200000, "Valoración": 7},
    "Enzo Fernández": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 10000000, "Valoración": 6},
    "Uvita Fernandez": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 500000, "Valoración": 6},
    "Martin heinze": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}
lanus_plantel = {
    "Lautaro Morales": {"Edad": 22, "Posición": "Portero", "Valor de Mercado": 1500000, "Valoración": 7},
    "Lucas Acosta": {"Edad": 26, "Posición": "Portero", "Valor de Mercado": 800000, "Valoración": 6},
    "Nicolás Morgantini": {"Edad": 27, "Posición": "Defensor", "Valor de Mercado": 900000, "Valoración": 7},
    "Alexis Pérez": {"Edad": 28, "Posición": "Defensor", "Valor de Mercado": 1200000, "Valoración": 7},
    "Ezequiel Muñoz": {"Edad": 31, "Posición": "Defensor", "Valor de Mercado": 1000000, "Valoración": 6},
    "Brian Aguirre": {"Edad": 23, "Posición": "Defensor", "Valor de Mercado": 800000, "Valoración": 6},
    "Tomás Belmonte": {"Edad": 23, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 8},
    "Facundo Pérez": {"Edad": 20, "Posición": "Volante", "Valor de Mercado": 1500000, "Valoración": 7},
    "Alexis Pérez": {"Edad": 26, "Posición": "Volante", "Valor de Mercado": 1200000, "Valoración": 7},
    "Pedro De La Vega": {"Edad": 20, "Posición": "Volante", "Valor de Mercado": 2000000, "Valoración": 8},
    "José Sand": {"Edad": 41, "Posición": "Delantero", "Valor de Mercado": 800000, "Valoración": 7},
    "Nicolás Orsini": {"Edad": 26, "Posición": "Delantero", "Valor de Mercado": 1800000, "Valoración": 7},
    "Franco Orozco": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 1000000, "Valoración": 6},
    "Matías Esquivel": {"Edad": 21, "Posición": "Delantero", "Valor de Mercado": 900000, "Valoración": 6},
    "Ignacio Cechi": {"Edad": 22, "Posición": "Volante", "Valor de Mercado": 600000, "Valoración": 6},
    "Brian Aguirre": {"Edad": 24, "Posición": "Defensor", "Valor de Mercado": 600000, "Valoración": 6}
}